# Generated by Django 6.0.3 on 2026-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_id", models.CharField(max_length=128, unique=True)),
                ("chapter_name", models.CharField(max_length=255)),
                ("chapter_difficulty", models.FloatField()),
                ("expected_completion_time_seconds", models.PositiveIntegerField()),
                ("prerequisites_csv", models.TextField(default="")),
            ],
            options={
                "managed": False,
            },
        ),
    ]
