# Generated by Django 6.0.3 on 2026-03-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=64)),
                ("chapter_id", models.CharField(max_length=128)),
                ("performance_score", models.FloatField()),
                ("confidence_score", models.FloatField()),
                ("learning_state", models.CharField(max_length=16)),
                ("diagnosis", models.JSONField(default=dict)),
                ("recommendation", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
